security:
    
    firewalls:
        # Firewall de la parte de administración o backend
        backend:
            pattern:        ^/backend
            provider:       administradores
            http_basic:     ~
        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                default_target_path: /usuario/
                always_use_default_target_path: true
            logout:
                path:       usuario_logout
                invalidate_session: false
            remember_me:
                key:        petlost1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
    
    access_control:
        - { path: ^/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/backend/*,         roles: ROLE_ADMIN }
    
    encoders:
        Petlost\UsuarioBundle\Entity\Usuario:        { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: sha512
    
    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: Petlost\UsuarioBundle\Entity\Usuario, property: email }
        # Usuarios del backend
        administradores:
            memory:
                users:
                    # user = admin, pass = 1234
                    admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USUARIO, ROLE_ALLOWED_TO_SWITCH]